import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { RunContext, Scenario } from "../lib/types.js";
import { ensureOk, http } from "../lib/http.js";

export const kodyRulesCreateAndApply: Scenario = {
    id: "kody-rules-create-and-apply",
    title: "A Kody Rule is created and applied to a fresh PR",
    priority: "P0",
    appliesTo: {
        target: ["cloud", "self-hosted"],
        provider: ["github", "gitlab", "bitbucket", "azure-devops"],
        license: ["paid", "license-paid"],
    },
    timeoutSec: 1200,
    async run(ctx: RunContext) {
        ctx.assert(ctx.tenant, "scenario requires a tenant");

        const session = await ctx.kodus.login(ctx.tenant!);
        await ctx.kodus.registerIntegration(session);
        const repo = await ctx.kodus.registerRepo(session);
        await ctx.kodus.finishOnboarding(session, repo);

        const ruleName = `e2e-rule-${ctx.runId.slice(0, 8)}-${randomUUID().slice(0, 6)}`;
        const ruleInstruction =
            "Forbid usage of the literal string TODO_REMOVE_ME in any source file.";

        const ruleResp = await http<{
            data?: { uuid?: string; id?: string };
        }>(
            `${ctx.target.apiBaseUrl}/kody-rules`,
            {
                method: "POST",
                headers: { Authorization: `Bearer ${session.accessToken}` },
                body: {
                    teamId: session.teamId,
                    repositoryId: String(repo.id),
                    title: ruleName,
                    rule: ruleInstruction,
                    severity: "HIGH",
                    status: "active",
                },
                timeoutMs: 30_000,
            },
        );
        ensureOk(ruleResp, "kody-rules:create");
        const ruleId = ruleResp.body.data?.uuid ?? ruleResp.body.data?.id;

        const branch = `kodus-e2e/kody-rules-${ctx.runId.slice(0, 8)}-${Date.now()}`;
        const violationContent = [
            "// Generated by Kodus E2E for kody-rules scenario",
            "function feature() {",
            "    // TODO_REMOVE_ME: still pending implementation",
            "    return 42;",
            "}",
            "",
            "module.exports = { feature };",
        ].join("\n");

        const opened = await ctx.provider.openPR({
            branch,
            title: `Kodus E2E: kody-rules ${ruleName}`,
            body: `Automated PR opened by Kodus E2E run ${ctx.runId} to validate rule ${ruleName}.`,
            fixtureFiles: {
                "kodus-e2e/rule-violation.js": violationContent,
                "kodus-e2e/README.md": `Run ${ctx.runId} — rule ${ruleName}`,
            },
        });

        try {
            const review = await ctx.provider.pollForReview(
                { number: opened.number },
                { sinceIso: new Date(0).toISOString(), timeoutSec: 720 },
            );

            ctx.assert(
                review.reviewComments + review.issueComments + review.reviews > 0,
                `No review activity on PR ${opened.url} within timeout`,
            );

            const sample = (review.sample ?? "").toLowerCase();
            const mentionsRule =
                sample.includes(ruleName.toLowerCase()) ||
                sample.includes("todo_remove_me") ||
                sample.includes("kody rule") ||
                sample.includes("rule violation");

            writeFileSync(
                join(ctx.artifactDir, "review-sample.txt"),
                review.sample ?? "(no sample captured)",
            );

            return {
                ruleId,
                ruleName,
                pr: opened,
                review,
                rulementioned: mentionsRule,
            };
        } finally {
            try {
                await ctx.provider.closePR(opened);
            } catch (err) {
                /* best effort */
            }
            if (ruleId) {
                try {
                    await http(
                        `${ctx.target.apiBaseUrl}/kody-rules/${ruleId}`,
                        {
                            method: "DELETE",
                            headers: {
                                Authorization: `Bearer ${session.accessToken}`,
                            },
                        },
                    );
                } catch {
                    /* best effort */
                }
            }
        }
    },
};

export default kodyRulesCreateAndApply;
